# Generated by Django 5.2.7 on 2025-10-16 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_digestarticle_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digestarticle',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digest_article', to='news.article'),
        ),
    ]
