# Generated by Django 5.2.7 on 2025-10-17 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_digestarticle_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='link',
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name='digest',
            name='name',
            field=models.CharField(unique=True),
        ),
        migrations.AlterField(
            model_name='newssource',
            name='rss_url',
            field=models.URLField(unique=True),
        ),
    ]
